name = "rarecontext"
compatibility_date = "2025-03-07"
dev.port = 3000
routes = [
  { pattern = "rarecontext.com", custom_domain = true },
  { pattern = "www.rarecontext.com", custom_domain = true }
]
assets.directory = "./"
